Add suggestions
See https://github.com/toltec-dev/toltec/pull/136\#issuecomment-751291106

diff --git a/package/rmx/package b/package/rmx/package
--- a/package/rmx/package
+++ b/package/rmx/package
@@ -2,17 +2,17 @@
 # Copyright (c) 2020 The Toltec Contributors
 # SPDX-License-Identifier: MIT
 
-pkgnames=(rm1-only rm2-only)
+pkgnames=(rm1 rm2)
 pkgdesc="Ensure packages are not installed on the wrong device"
-pkgver=0.1.0-1
-url=http://0.0.0.0/
-timestamp=2020-11-06T09:35Z
+pkgver=0.1.0-2
+url=https://github.com/toltec-dev/toltec
+timestamp=2020-12-25T22:21Z
 section=meta
 maintainer="Linus K. <linus@cosmos-ink.net>"
 license=MIT
 
-rm1-only() {
-    conflicts=(rm2-only)
+rm1() {
+    conflicts=(rm2)
 
     package() { :; }
 
@@ -24,14 +24,16 @@ rm1-only() {
 
         if [[ ! "${supported_machine_names[*]}" =~ $actual_machine_name ]]; then
             echo "Your devices got identified as: $actual_machine_name" >&2
-            echo "You are attempting to install a package that only works on the reMarkable 1." >&2
+            echo "You are attempting to install the package \"rm1\" on something else." >&2
+            echo "This package should not get installed here. Please uninstall it now:" >&2
+            echo "$ opkg remove rm1  (add --force-remove it fails)" >&2
             exit 1
         fi
     }
 }
 
-rm2-only() {
-    conflicts=(rm1-only)
+rm2() {
+    conflicts=(rm1)
 
     package() { :; }
 
@@ -43,7 +45,9 @@ rm2-only() {
 
         if [[ ! "${supported_machine_names[*]}" =~ $actual_machine_name ]]; then
             echo "Your devices got identified as: $actual_machine_name" >&2
-            echo "You are attempting to install a package that only works on the reMarkable 2." >&2
+            echo "You are attempting to install the package \"rm2\" on something else." >&2
+            echo "This package should not get installed here. Please uninstall it now:" >&2
+            echo "$ opkg remove rm2  (add --force-remove it fails)" >&2
             exit 1
         fi
     }
