Switch to using opkg compare-versions

diff --git a/package/toltec-bootstrap/toltecctl b/package/toltec-bootstrap/toltecctl
--- a/package/toltec-bootstrap/toltecctl
+++ b/package/toltec-bootstrap/toltecctl
@@ -85,19 +85,33 @@ check-version() {
             "$toltec_srv_root"/"$check_branch"/Compatibility \
             2> /dev/null
     )"; then
-        echo "Unable to fetch version compatibility information"
+        echo "Unable to fetch version compatibility information, make sure you have a stable Wi-Fi connection"
         return 2
     fi
 
     supported_version="$(
         echo "$compat" | awk "/$current_model-max-os-version/{ print \$2 }"
     )"
-
-    if ((current_version > supported_version)); then
-        echo "You’re running an unsupported OS version: $current_version"
-        echo "Toltec currently supports versions up to $supported_version"
-        echo "Please monitor Toltec releases for upcoming support"
-        return 1
+    local opkg_path=/home/root/.local/bin/opkg
+    if ! type -P opkg > /dev/null; then
+        # Fetch standalone opkg used to uninstall packages
+        if ! install-standalone-opkg "$opkg_path"; then
+            return 1
+        fi
+        if "$opkg_path" compare-versions $current_version '>>' $supported_version > /dev/null; then
+            echo "You’re running an unsupported OS version: $current_version"
+            echo "Toltec currently supports versions up to $supported_version"
+            echo "Please monitor Toltec releases for upcoming support"
+            return 1
+        fi
+        rm -f "$opkg_path"
+    else
+        if opkg compare-versions $current_version '>>' $supported_version > /dev/null; then
+            echo "You’re running an unsupported OS version: $current_version"
+            echo "Toltec currently supports versions up to $supported_version"
+            echo "Please monitor Toltec releases for upcoming support"
+            return 1
+        fi
     fi
 
     return 0
@@ -393,10 +407,9 @@ list-installed-ordered() {
     # tsort reports errors if there are dependency cycles, we ignore them
 }
 
-# Remove Toltec completely
-uninstall() {
-    # Fetch standalone opkg used to uninstall packages
-    local opkg_path=/home/root/.local/bin/opkg
+# Install standalone opkg binary
+install-standalone-opkg(){
+    local opkg_path="{$1-/home/root/.local/bin/opkg}"
     local opkg_remote=https://bin.entware.net/armv7sf-k3.2/installer/opkg
 
     if ! wget --no-verbose "$opkg_remote" --output-document "$opkg_path"; then
@@ -405,6 +418,15 @@ uninstall() {
     fi
 
     chmod u+x "$opkg_path"
+}
+
+# Remove Toltec completely
+uninstall() {
+    local opkg_path=/home/root/.local/bin/opkg
+    # Fetch standalone opkg used to uninstall packages
+    if ! install-standalone-opkg "$opkg_path"; then
+        return 1
+    fi
 
     # Remove installed packages in reverse dependency order
     list-installed-ordered | while read -r pkgname; do
