Manage Opkg configuration with toltecctl
This is a three-headed monster of a PR, addressing three distinct yet linked issues.

New toltecctl features
----------------------

At its core, this PR extends the toltecctl script (provided by toltec-bootstrap, introduced in #356) and enables it to manage the Opkg configuration, i.e., switch branches and migrate the configuration when needed. To achieve this without risking to overwrite custom config directives added by users, a split configuration approach is taken (as suggested by @Eeems):

* The main `/opt/etc/opkg.conf` file is automatically generated by concatenating the files in the `/opt/etc/opkg.conf.d/` folder (in lexicographic order).
* The file `/opt/etc/opkg.conf.d/10-entware.conf` configures the Entware repository and architecture names.
* The file `/opt/etc/opkg.conf.d/15-toltec.conf` configures the Toltec repository and architecture names.
* Users may create new files in `/opt/etc/opkg.conf.d` to add their custom directives.

New toltecctl commands are made available to users for managing the Opkg configuration:

* `toltecctl generate-opkg-conf` - Regenerates the main config file and automatically runs `opkg update` if the config changed
* `toltecctl switch-branch [BRANCH]` - Switches the current Toltec branch, rebuilds the config file and runs `opkg update`

This new `toltecctl switch-branch` fixes #341. A confirmation prompt is shown when someone tries to switch to the `testing` branch to warn them of the potential instability.

Bootstrap script revamp
-----------------------

This fixes #141.

With the previously mentioned additions, toltecctl now almost fully duplicates the features of the bootstrap script: it can create bind mounts, initialize the Opkg configuration, and define the user’s PATH. This PR therefore also contains a new bootstrap script that fetches the `toltec-bootstrap` package (containing toltecctl) first, and then uses its functions to perform the install, instead of reimplementing the same logic. By consolidating the features and variables of the two scripts, I hope to reduce the surface for potential bugs. This also makes it easier to add migrations to the `toltec-bootstrap` package, since it shares the code of the bootstrap script that’s used for new installs.

Migration to the new Opkg configuration
---------------------------------------

Building on the toltecctl improvements, a config migration logic was added to the `toltec-bootstrap` package’s configure function. This will automatically migrate single-opkg.conf-file installs to the new split config layout, while keeping the currently configured branch.

This migration is also able to transition configs using the old repository layout (with a single folder containing all packages) to the new arch-subfolder layout. By publishing the new toltec-bootstrap package to the root folder of the stable branch, this will solve #370.

diff --git a/package/toltec-bootstrap/toltecctl b/package/toltec-bootstrap/toltecctl
--- a/package/toltec-bootstrap/toltecctl
+++ b/package/toltec-bootstrap/toltecctl
@@ -10,11 +10,52 @@ toltec_src=/home/root/.entware
 # Path where Toltec is mounted
 toltec_dest=/opt
 
+# Path to Opkg configuration
+opkg_conf="$toltec_dest"/etc/opkg.conf
+opkg_conf_dir="$toltec_dest"/etc/opkg.conf.d
+
 # Start and end markers of Toltec-managed section in bashrc
 bashrc_path=/home/root/.bashrc
 bashrc_start_marker="# Added by Toltec bootstrap (do not modify!)"
 bashrc_old_start_marker="# Path added by Toltec bootstrap"
 bashrc_end_marker="# End of Toltec bootstrap additions"
+
+# Identify which reMarkable model we’re currently running on
+#
+# Output: One of the following strings
+#
+# rm1 - for reMarkable 1
+# rm2 - for reMarkable 2
+# unknown
+identify-model() {
+    local device_id
+    device_id="$(cat /sys/devices/soc0/machine)"
+
+    case $device_id in
+        "reMarkable 1.0" | "reMarkable Prototype 1")
+            echo "rm1"
+            ;;
+        "reMarkable 2.0")
+            echo "rm2"
+            ;;
+        *)
+            echo "unknown"
+            ;;
+    esac
+}
+
+# Get the path for a systemd bind mount unit
+#
+# Arguments:
+#
+# $1 - Mount point
+#
+# Output:
+#
+# Path at which the definition of a bind mount on $1 should reside
+get-bind-mount-path() {
+    echo "/lib/systemd/system/$(systemd-escape --path "$1").mount"
+}
 
 # Create or update a bind mount systemd unit and enable it
 #
@@ -23,10 +64,10 @@ bashrc_end_marker="# End of Toltec bootstrap additions"
 # $1 - Source directory
 # $2 - Mount point
 add-bind-mount() {
-    local unit_name
     local unit_path
-    unit_name="$(systemd-escape --path "$2").mount"
-    unit_path="/lib/systemd/system/$unit_name"
+    local unit_name
+    unit_path="$(get-bind-mount-path "$2")"
+    unit_name="$(basename "$unit_path")"
 
     if [[ -e $unit_path ]]; then
         echo "Bind mount configuration for '$2' already exists, updating"
@@ -60,10 +101,10 @@ UNIT
 #
 # $1 - Mount point
 remove-bind-mount() {
-    local unit_name
     local unit_path
-    unit_name="$(systemd-escape --path "$1").mount"
-    unit_path="/lib/systemd/system/$unit_name"
+    local unit_name
+    unit_path="$(get-bind-mount-path "$1")"
+    unit_name="$(basename "$unit_path")"
 
     if [[ ! -e $unit_path ]]; then
         echo "No existing bind mount for '$1'"
@@ -113,8 +154,8 @@ reinstall-root() {
     set -u
 }
 
+# Remove all PATH definitions for /opt in bashrc
 clean-path() {
-    # Remove all PATH definitions for /opt in bashrc
     if [[ -f $bashrc_path ]]; then
         sed -i "/^$bashrc_start_marker\$/,/^$bashrc_end_marker\$/d" "$bashrc_path"
         sed -i "/^$bashrc_old_start_marker\$/!b;n;d" "$bashrc_path"
@@ -123,8 +164,11 @@ clean-path() {
     fi
 }
 
+# Add/update PATH declarations in bashrc to include Toltec binaries
 set-path() {
-    # Fix PATH contents to include Toltec binaries
+    local old_path
+    old_path="$(bash -l -c "echo \$PATH")"
+
     clean-path
     cat >> "$bashrc_path" << SHELL
 $bashrc_start_marker
@@ -133,22 +177,110 @@ $bashrc_end_marker
 SHELL
 
     # Warn user if PATH contents have changed
-    old_path="$PATH"
+    local new_path
     new_path="$(bash -l -c "echo \$PATH")"
+
     if [[ $old_path != "$new_path" ]]; then
         echo "Please restart your SSH session or run 'exec bash -l' to use Toltec"
     fi
 }
 
+# Rebuild the Opkg configuration file from split config files
+#
+# Exit code:
+#
+# 0 - If the configuration file has changed (in which case
+#     `opkg update` needs to be run)
+# 1 - If there were no changes
+generate-opkg-conf() {
+    local old_opkg_conf
+    old_opkg_conf="$(mktemp)"
+
+    if [[ -f $opkg_conf ]]; then
+        mv "$opkg_conf" "$old_opkg_conf"
+    else
+        touch "$old_opkg_conf"
+    fi
+
+    cat > "$opkg_conf" << CONF
+# Opkg configuration
+# Generated by toltecctl (do not modify!)
+
+# Define custom configuration in files under the '$opkg_conf_dir' directory
+# then run \`toltecctl generate-opkg-conf\` to regenerate this file
+
+dest root /
+dest ram /opt/tmp
+lists_dir ext /opt/var/opkg-lists
+option tmp_dir /opt/tmp
+
+CONF
+
+    for conf in "$opkg_conf_dir"/*; do
+        echo "# $conf"
+        sed -e '/^#/d' -e '/^$/d' "$conf"
+        echo
+    done >> "$opkg_conf"
+
+    ! diff "$old_opkg_conf" "$opkg_conf" > /dev/null
+}
+
+# Create the Opkg configuration file for fetching Entware packages
+create-entware-conf() {
+    mkdir -p "$opkg_conf_dir"
+    cat > "$opkg_conf_dir"/10-entware.conf << CONF
+# Entware repository configuration
+# Managed by Toltec (do not modify!)
+
+# Define custom configuration in other files in this directory
+# then run \`toltecctl generate-opkg-conf\` to regenerate '$opkg_conf'
+
+arch all 100
+arch armv7-3.2 160
+src/gz entware https://bin.entware.net/armv7sf-k3.2
+CONF
+}
+
+# Set the Toltec branch for this installation
+# (generate-opkg-conf must be run afterwards to rebuild the main config file)
+#
+# Arguments:
+#
+# $1 - Name of the branch to use (either stable or testing)
+switch-branch() {
+    local branch="${1:-stable}"
+    local model
+    model="$(identify-model)"
+
+    if [[ $model = "unknown" ]]; then
+        echo "You’re running an unsupported or unrecognised device"
+        exit 1
+    fi
+
+    mkdir -p "$opkg_conf_dir"
+    cat >| "$opkg_conf_dir"/15-toltec.conf << CONF
+# Toltec repository configuration
+# Generated by toltecctl (do not modify!)
+
+# Use \`toltecctl switch-branch [stable|testing]\` to
+# switch to a different Toltec branch
+
+arch rmall 200
+src/gz toltec-rmall https://toltec-dev.org/$branch/rmall
+arch $model 250
+src/gz toltec-$model https://toltec-dev.org/$branch/$model
+CONF
+}
+
+# Re-enable Toltec install after system update
 reenable() {
-    # Re-enable Toltec install after system update
     add-bind-mount "$toltec_src" "$toltec_dest"
     reinstall-root
     set-path
 }
 
-uninstall-force() {
-    # Remove all installed packages without prompting user
+# Remove all installed packages
+uninstall() {
     opkg remove --force-depends --force-remove "*"
     systemctl daemon-reload
 
@@ -169,48 +301,72 @@ uninstall-force() {
     reboot
 }
 
-uninstall() {
-    # Remove all installed packages after prompting user
-    if [[ $# -gt 0 && ($1 = "-f" || $1 = "--force") ]]; then
-        uninstall-force
-        return
-    fi
-
-    read -p "This will wipe out all files in '$toltec_dest'. Continue? [y/n] " -n 1 -r
-    echo
-
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        uninstall-force
-        return
-    fi
-
-    echo "Canceled"
-}
-
 help() {
     echo "Usage: $(basename "$0") COMMAND
 Manage your Toltec install. Available commands:
 
-    reenable        Re-enable Toltec after a system update.
-    set-path        Fix PATH value if needed.
-    uninstall       Permanently remove Toltec."
+    generate-opkg-conf      Rebuild the Opkg configuration file.
+    switch-branch [BRANCH]  Change the current branch to BRANCH.
+    reenable                Re-enable Toltec after a system update.
+    uninstall               Permanently remove Toltec."
 }
 
-if [[ $# -eq 0 ]]; then
-    help
-    exit 1
-fi
-
-action="$1"
-shift
-
-case $action in
-    reenable) reenable "$@" ;;
-    set-path) set-path "$@" ;;
-    uninstall) uninstall "$@" ;;
-    *)
-        echo -e "Error: Invalid command '$action'\n"
+if [[ $0 = "${BASH_SOURCE[0]}" ]]; then
+    if [[ $# -eq 0 ]]; then
         help
         exit 1
-        ;;
-esac
+    fi
+
+    action="$1"
+    shift
+
+    case $action in
+        generate-opkg-conf)
+            generate-opkg-conf && opkg update
+            ;;
+
+        switch-branch)
+            if [[ ($# -eq 1 && $1 = "testing") || ($# -eq 2 && $1 = "testing" && $2 != "-f" && $2 != "--force") ]]; then
+                cat <<MSG
+Using packages from the testing branch may cause breakage or data loss.
+Please make sure you read the following before switching to testing:
+
+    <https://github.com/toltec-dev/toltec/blob/stable/docs/branches.md>
+
+MSG
+                read -p "Continue? [y/n] " -n 1 -r
+                echo
+
+                if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+                    echo "Canceled"
+                    exit 1
+                fi
+            fi
+            switch-branch "${1:-stable}"
+            generate-opkg-conf && opkg update
+            ;;
+
+        reenable)
+            reenable
+            ;;
+
+        uninstall)
+            if [[ $# -eq 0 || ($1 != "-f" && $1 != "--force") ]]; then
+                read -p "This will wipe out all files in '$toltec_dest'. Continue? [y/n] " -n 1 -r
+                echo
+
+                if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+                    echo "Canceled"
+                    exit 1
+                fi
+            fi
+            uninstall
+            ;;
+
+        *)
+            echo -e "Error: Invalid command '$action'\n"
+            help
+            exit 1
+            ;;
+    esac
+fi
