Move maintainer scripts definition to recipe file
Fixes #60.

Recipe files can define 5 new functions, `preinstall`, `configure`,
`preremove`, `postremove`, `preupgrade` and `postupgrade`, which are
used to define the `preinst`, `postinst`, `prerm` and `postrm`
maintainer scripts.

When installing a new package, the following happens:

* The package files are unpacked (but not installed)
* `preinstall` is called
* The package files are installed into place
* `configure` is called

When removing an installed package, the following happens:

* `preremove` is called
* The package files are removed (except configuration files)
* `postremove` is called

When upgrading a package from version A to B, the following happens:

* `preupgrade B` is called from version A
* Old package files are removed (except configuration files)
* `postupgrade B` is called from version A
* New package files are unpacked and installed
* `configure` is called from version B

This PR updates draft, remux, oxide and plato which were previously
using old-style maintainer scripts.

diff --git a/package/draft/package b/package/draft/package
--- a/package/draft/package
+++ b/package/draft/package
@@ -2,7 +2,7 @@
 pkgname=draft
 pkgdesc="Launcher which wraps around the standard interface"
 url=https://github.com/dixonary/draft-reMarkable
-pkgver=0.2.0-12
+pkgver=0.2.0-13
 timestamp=2020-07-20T10:23Z
 section=launchers
 maintainer="Mattéo Delabre <spam@delab.re>"
@@ -39,4 +39,60 @@ package() {
     mv "$pkgdir"/opt/etc/draft/{99-,}shutdown
 
     install -D -m 644 -t "$pkgdir"/lib/systemd/system "$srcdir"/draft.service
+}
+
+# Check whether a systemd unit exists and is enabled
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Exit code:
+#
+# 0 if the unit exists and is enabled, 1 otherwise
+is-enabled() {
+    # Note that we must invert the condition so that the exit code indicates
+    # a failure when the unit exists and is disabled or when the unit does
+    # not exist
+    ! systemctl list-unit-files "$1" | awk "/$1/{exit \$2 == \"enabled\"}"
+}
+
+# Get a list of systemd units with which the given unit conflicts
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Output:
+#
+# List of conflicting units
+get-conflicts() {
+    systemctl show "$1" | awk -F'=' '/^Conflicts=/{print $2}'
+}
+
+configure() {
+    systemctl daemon-reload
+
+    if ! is-enabled "$pkgname.service"; then
+        echo ""
+        echo "Run the following command(s) to use $pkgname as your launcher"
+
+        for conflict in $(get-conflicts "$pkgname.service"); do
+            if is-enabled "$conflict"; then
+                echo "$ systemctl disable --now ${conflict/.service/}"
+            fi
+        done
+
+        echo "$ systemctl enable --now $pkgname"
+        echo ""
+    fi
+}
+
+preremove() {
+    echo "Disabling $pkgname"
+    systemctl disable --now "$pkgname"
+}
+
+postremove() {
+    systemctl daemon-reload
 }
diff --git a/package/oxide/package b/package/oxide/package
--- a/package/oxide/package
+++ b/package/oxide/package
@@ -2,7 +2,7 @@
 pkgname=oxide
 pkgdesc="Launcher application"
 url=https://github.com/Eeems/oxide
-pkgver=2.0~alpha-2
+pkgver=2.0~alpha-3
 timestamp=2020-09-11T05:33Z
 section=launchers
 maintainer="raisjn <of.rajsn@gmail.com>"
@@ -19,4 +19,60 @@ build() {
 
 package() {
     cp -ar "$srcdir"/release/* "$pkgdir"
+}
+
+# Check whether a systemd unit exists and is enabled
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Exit code:
+#
+# 0 if the unit exists and is enabled, 1 otherwise
+is-enabled() {
+    # Note that we must invert the condition so that the exit code indicates
+    # a failure when the unit exists and is disabled or when the unit does
+    # not exist
+    ! systemctl list-unit-files "$1" | awk "/$1/{exit \$2 == \"enabled\"}"
+}
+
+# Get a list of systemd units with which the given unit conflicts
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Output:
+#
+# List of conflicting units
+get-conflicts() {
+    systemctl show "$1" | awk -F'=' '/^Conflicts=/{print $2}'
+}
+
+configure() {
+    systemctl daemon-reload
+
+    if ! is-enabled "$pkgname.service"; then
+        echo ""
+        echo "Run the following command(s) to use $pkgname as your launcher"
+
+        for conflict in $(get-conflicts "tarnish.service"); do
+            if is-enabled "$conflict"; then
+                echo "$ systemctl disable --now ${conflict/.service/}"
+            fi
+        done
+
+        echo "$ systemctl enable --now tarnish"
+        echo ""
+    fi
+}
+
+preremove() {
+    echo "Disabling $pkgname"
+    systemctl disable --now tarnish
+}
+
+postremove() {
+    systemctl daemon-reload
 }
diff --git a/package/remux/package b/package/remux/package
--- a/package/remux/package
+++ b/package/remux/package
@@ -2,7 +2,7 @@
 pkgname=remux
 pkgdesc="App launcher that supports multi-tasking applications"
 url=https://github.com/rmkit-dev/rmkit
-pkgver=0.0.1-14
+pkgver=0.0.1-15
 timestamp=2020-09-21T01:41+00:00
 section=launchers
 maintainer="raisjn <of.rajsn@gmail.com>"
@@ -21,4 +21,60 @@ package() {
     install -d "$pkgdir"/opt/usr/bin
     install -D -m 755 "$srcdir"/src/build/remux "$pkgdir"/opt/bin/remux
     install -D -m 644 "$srcdir"/src/remux/remux.service "$pkgdir"/etc/systemd/system/remux.service
+}
+
+# Check whether a systemd unit exists and is enabled
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Exit code:
+#
+# 0 if the unit exists and is enabled, 1 otherwise
+is-enabled() {
+    # Note that we must invert the condition so that the exit code indicates
+    # a failure when the unit exists and is disabled or when the unit does
+    # not exist
+    ! systemctl list-unit-files "$1" | awk "/$1/{exit \$2 == \"enabled\"}"
+}
+
+# Get a list of systemd units with which the given unit conflicts
+#
+# Arguments:
+#
+# $1 - Full name of the systemd unit, e.g. "xochitl.service"
+#
+# Output:
+#
+# List of conflicting units
+get-conflicts() {
+    systemctl show "$1" | awk -F'=' '/^Conflicts=/{print $2}'
+}
+
+configure() {
+    systemctl daemon-reload
+
+    if ! is-enabled "$pkgname.service"; then
+        echo ""
+        echo "Run the following command(s) to use $pkgname as your launcher"
+
+        for conflict in $(get-conflicts "$pkgname.service"); do
+            if is-enabled "$conflict"; then
+                echo "$ systemctl disable --now ${conflict/.service/}"
+            fi
+        done
+
+        echo "$ systemctl enable --now $pkgname"
+        echo ""
+    fi
+}
+
+preremove() {
+    echo "Disabling $pkgname"
+    systemctl disable --now "$pkgname"
+}
+
+postremove() {
+    systemctl daemon-reload
 }
