Do not restore the binary if it has changed

diff --git a/package/ddvk-hacks/package b/package/ddvk-hacks/package
--- a/package/ddvk-hacks/package
+++ b/package/ddvk-hacks/package
@@ -129,8 +129,8 @@ configure() {
             ;;
         *)
             echo
-            echo "The version the device is running is not supported, yet."
-            echo "    Build date: $build_date"
+            echo "Error: The version the device is running is not supported, yet."
+            echo "Build date: $build_date"
             echo
             exit 1
             ;;
@@ -143,7 +143,7 @@ configure() {
     echo
 
     if ! sha1sum -c <(echo "$original_hash  $_xochitl_path") > /dev/null 2>&1; then
-        echo "Invalid Xochitl checksum"
+        echo "Error: Invalid Xochitl checksum"
         echo "Maybe ddvk-hacks are already installed?"
         echo
         exit 1
@@ -177,8 +177,15 @@ preremove() {
 
     echo
     echo "Restoring the original Xochitl binary"
-    cp "$_backup_path" "$_xochitl_path"
-    rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
+
+    if ! diff "$_xochitl_path" "$_patched_path" > /dev/null 2>&1; then
+        echo "Warning: Xochitl binary has changed!"
+        echo "Not restoring the backup"
+    else
+        cp "$_backup_path" "$_xochitl_path"
+        rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
+    fi
+
     echo
 }
 
@@ -194,7 +201,14 @@ preupgrade() {
 
     echo
     echo "Restoring the original Xochitl binary before upgrading"
-    cp "$_backup_path" "$_xochitl_path"
-    rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
+
+    if ! diff "$_xochitl_path" "$_patched_path" > /dev/null 2>&1; then
+        echo "Warning: The Xochitl binary has changed!"
+        echo "Not restoring the backup"
+    else
+        cp "$_backup_path" "$_xochitl_path"
+        rm -rf /home/root/.cache/remarkable/xochitl/qmlcache/*
+    fi
+
     echo
 }
