Update rm2fb
Only restart xochitl if it's running.
Reset crashnum before restarting xochtil.
Modify preremove message based on xochitl's state.

diff --git a/package/rm2fb/package b/package/rm2fb/package
--- a/package/rm2fb/package
+++ b/package/rm2fb/package
@@ -46,11 +46,20 @@ package() {
 configure() {
     systemctl daemon-reload
     systemctl enable rm2fb --now
-    systemctl restart xochitl
+    # Restart xochitl if it's running
+    if systemctl --quiet is-active xochitl; then
+        # Reset the crash count so we don't trigger remarkable-fail
+        echo "0" > /tmp/crashnum
+        systemctl restart xochitl
+    fi
 }
 
 preremove() {
-    echo "make sure to re-enable xochitl with 'systemctl enable xochitl --now'"
-    echo "and to disable / uninstall any launchers like draft, oxide or remux before"
+    echo -n "make sure "
+    if ! systemctl list-units --full -all | grep -Fq 'xochitl.service'; then
+        echo "to re-enable xochitl with 'systemctl enable xochitl --now'"
+        echo -n "and "
+    fi
+    echo "to disable / uninstall any launchers like draft, oxide or remux before"
     echo "rebooting your tablet to complete the uninstallation"
 }
