Stable merge window for week 03 of 2020
New packages:

* decay 2.1\~beta-1

Updated packages:

* draft 0.2.0-16 → 0.2.0-17
    - Fix install script asking to disable shutdown.target
* erode 2.0.3\~beta-1 → 2.1\~beta-1
    - Add .oxide file
    - Automatically reload oxide on install
* fret 2.0.3\~beta-1 → 2.1\~beta-1
    - Add .oxide file
    - Automatically reload oxide on install
* oxide 2.0.3\~beta-1 → 2.1\~beta-1
    - Add .oxide file
    - Automatically reload oxide on install
* rot 1.0.0 → 2.1\~beta-1
    - Fix wrong version
* tarnish 2.0.3\~beta-1 → 2.1\~beta-1
    - Fix install script asking to disable shutdown.target
* koreader 2020.12-2 → 2020.12-3
    - Add .oxide file
    - Automatically reload oxide on install
    - Remove warning relative to Oxide
* plato 0.9.1-13 → 0.9.13-1
* genie 0.1.0-1 → 0.1.1-1
* simple 0.1.0-3 → 0.1.1-1
* remux 0.1.5-1 → 0.1.6-2
* toltec-bootstrap 0.0.1-2 → 0.0.1-3
    - Update wget to 1.21.1
* xochitl 0.0.0-2 → 0.0.0-3
    - Add .oxide file
    - Automatically reload oxide on install

Install:

* Update wget to 1.21.1
* Upgrade old opt.mount bind mount from remarkable_entware
* Keep branch from existing install if applicable

Documentation:

* Link to code of conduct and security policy.

Tooling:

* Add flag field to disable auto stripping of binaries
* Send Discord notifications on update

diff --git a/scripts/install-lib b/scripts/install-lib
--- a/scripts/install-lib
+++ b/scripts/install-lib
@@ -23,6 +23,20 @@ is-enabled() {
     systemctl --quiet is-enabled "$1" 2> /dev/null
 }
 
+# Check whether a systemd unit is in an active state
+# ("running")
+#
+# Arguments:
+#
+# $1 - Name of the systemd unit, e.g. "xochitl.service" or "xochitl"
+#
+# Exit code:
+#
+# 0 if the unit exists and is enabled, 1 otherwise
+is-active() {
+    systemctl --quiet is-active "$1" 2> /dev/null
+}
+
 # Get a list of systemd units with which the given unit conflicts
 #
 # Arguments:
@@ -33,7 +47,10 @@ is-enabled() {
 #
 # List of conflicting units
 get-conflicts() {
-    systemctl show "$1" | awk -F'=' '/^Conflicts=/{print $2}'
+    # systemd automatically adds a conflict with "shutdown.target" to all
+    # service units (see systemd.service(5), section "Automatic Dependencies")
+    systemctl show "$1" | awk -F'=' '/^Conflicts=/{print $2}' \
+        | sed 's|\bshutdown.target\b||'
 }
 
 # Print instructions about how to enable a given systemd service and disable
@@ -54,4 +71,21 @@ how-to-enable() {
     done
 
     echo "$ systemctl enable --now ${1/.service/}"
+}
+
+# Reload Oxide applications if tarnish is running
+#
+# Output:
+#
+# Status message
+reload-oxide-apps() {
+    if ! is-active tarnish.service; then
+        return
+    fi
+    echo -n "Reloading Oxide applications: "
+    if ! /opt/bin/rot apps call reload 2> /dev/null; then
+        echo "Failed!"
+    else
+        echo "Done!"
+    fi
 }
