tooling: Make repo-check recurse in tar archives

diff --git a/scripts/lib b/scripts/lib
--- a/scripts/lib
+++ b/scripts/lib
@@ -50,6 +50,59 @@ rtar() {
         | gzip -9 --no-name - > "$1"
 }
 
+# Recursively compares two files, entering inside tar archives when possible
+#
+# Arguments:
+#
+# $1 - First file or tar archive to compare
+# $2 - Second file or tar archive to compare
+# $3 (optional) - Display name for the first file
+# $4 (optional) - Display name for the second file
+#
+# Return value:
+#
+# 0 if no difference, 1 if there is a difference
+tardiff() {
+    label1="${3:-$1}"
+    label2="${4:-$2}"
+
+    # Compare non-archive files
+    if ! tar -tf "$1" > /dev/null 2>&1; then
+        if ! diff=$(diff "$1" --label "$label1" "$2" --label "$label2"); then
+            echo "Files $label1 and $label2 differ:"
+            echo "$diff"
+            return 1
+        fi
+    # Compare tar archives
+    else
+        # See if they are equal byte to byte
+        if diff "$1" "$2" > /dev/null 2>&1; then
+            return 0
+        fi
+
+        # See if they contain the same files
+        if ! diff=$(diff <(tar -tf "$1") <(tar -tf "$2")); then
+            echo "Archives $label1 and $label contain different files:"
+            echo "$diff"
+            return 1
+        fi
+
+        # See if each file pair is identical
+        while IFS= read -r subfile; do
+            subfile1="$(mktemp)"
+            subfile2="$(mktemp)"
+
+            tar -xf "$1" "$subfile" -O > "$subfile1"
+            tar -xf "$2" "$subfile" -O > "$subfile2"
+
+            (tardiff \
+                "$subfile1" "$subfile2" \
+                "$label1" "$label2 -> $subfile")
+            rm "$subfile1" "$subfile2"
+        done < <(tar -tf "$1" | grep -e "[^/]$")
+    fi
+}
+
 # Curl command with flags suitable for scripting
 rcurl() {
     curl --fail --silent --tlsv1.2 "$@"
diff --git a/scripts/repo-check b/scripts/repo-check
--- a/scripts/repo-check
+++ b/scripts/repo-check
@@ -46,42 +46,20 @@ fi
 differs=
 subfiles=(./control.tar.gz ./data.tar.gz ./debian-binary)
 
+if [[ ! -f "$localrepo"/Packages ]]; then
+    error "Local repository is missing packages index"
+fi
+
 for localfile in "$localrepo"/*; do
     file="$(realpath --relative-to="$localrepo" "$localfile")"
     remotefileurl="$remoterepo"/"$file"
 
-    status "Comparing $file"
+    section "Checking $file"
 
     remotefile="$(mktemp)"
     rsecurl "$remotefileurl" -o "$remotefile"
 
-    if ! diff "$localfile" "$remotefile" > /dev/null; then
-        echo "! $file differs between the local and the remote repositories."
-
-        if [[ $file =~ \.ipk$ ]]; then
-            for subfile in "${subfiles[@]}"; do
-                # Compare non-archive subfiles normally
-                if [[ ! $subfile =~ \.tar\.gz$ ]]; then
-                    if ! diff > /dev/null \
-                            <(tar -axf "$localfile" "$subfile" -O) \
-                            <(tar -axf "$remotefile" "$subfile" -O); then
-                        echo "!> $subfile differs."
-                    fi
-                # First, compare the list of files in archive subfiles
-                elif ! filediff=$(diff \
-                        <(tar -axf "$localfile" "$subfile" -O | tar -tzvf -) \
-                        <(tar -axf "$remotefile" "$subfile" -O | tar -tzvf -)); then
-                    printf "!> The following files from %s inside %s differ:\n\n%s\n\n" \
-                        "$subfile" "$file" "$filediff"
-                # Otherwise, compare them as binary
-                elif ! diff > /dev/null \
-                        <(tar -axf "$localfile" "$subfile" -O) \
-                        <(tar -axf "$remotefile" "$subfile" -O); then
-                    echo "!> Files from $subfile inside $file are the same but the archives differ."
-                fi
-            done
-        fi
-
+    if ! tardiff "$localfile" "$remotefile" "local $file" "remote $file"; then
         differs=yes
     fi
 
@@ -91,5 +69,5 @@ done
 if [[ -n $differs ]]; then
     error "Some files differ"
 else
-    status "Done"
+    section "Successful"
 fi
