Stable merge for week 19 of 2023 (#693)
### Updated Packages
- `koreader` - 2023.04-1 (#672 #681)
- `display`, `rm2fb-client` - 0.0.31-1 (#680 #686)
  - If rm2fb fails to start on install, disable it to avoid soft-bricking the device
  - Add support for the following OS versions:
    - 3.2.2.1581
    - 3.2.3.1595
- `wordlet` - 0.0.2-2 (#670)
  - Swap M and N on keyboard
  - Fix image thumbnail code
- `harmony` - 0.2.2-1 (#670)
  - Fix exporting individual layers
- `simple` - 0.2.0-2 (#670)
  - Add "range" input widget
  - Add "canvas" widget
  - Less debug output
  - Make images clickable
  - Move 'timeout' to its own thread instead of jamming task queue
  - Ignore empty lines
- `remux` - 0.2.4-1 (#670)
  - Add "suspend" to remux FIFO api
- `rpncalc` - 0.0.3-2 (#670)
  - Make it more like the hp48
- `toltec-base` - 1.2-1 (#685)
  -  Only disable sys-subsystem-net-devices-usb1.device if on a reMarkable 1. On a reMarkable 2, this makes SSH over usb no longer available.
  - Make toltec-base properly clean itself up on uninstall
- `kernelctl` - 0.1-6 (#691)
  - Reset to the default kernel on uninstall so that `toltecctl uninstall` will return the device to a stock state
- `restream` - 1.2-1 (#688)
- `fbink`, `fbdepth`, and `fbink-doom` - 1.25.0-1 (#687)

**Note:** This doesn't change what OS version that toltec supports, as full support still requires `ddvk-hacks` to be updated, and for proper testing of various other packages.

diff --git a/package/display/package b/package/display/package
--- a/package/display/package
+++ b/package/display/package
@@ -4,11 +4,11 @@
 
 archs=(rm1 rm2)
 pkgnames=(display rm2fb-client)
-timestamp=2023-02-20T15:49:05Z
+timestamp=2023-04-16T20:53:38Z
 maintainer="raisjn <of.raisjn@gmail.com>"
 license=MIT
 url="https://github.com/ddvk/remarkable2-framebuffer"
-pkgver=1:0.0.30-1
+pkgver=1:0.0.31-2
 _release="${pkgver%-*}"
 _release="v${_release#*:}"
 _libver=1.0.1
@@ -23,7 +23,7 @@ source=(
     rm2fb-preload.env
 )
 sha256sums=(
-    bbd2acf8bc7d15082307c362985980e78cf1b48a69799aa602cf7dc3973339c7
+    c27081be9b4fa000e41489b42d53fb8254bd8bf348a34756799488827dbc0f0b
     SKIP
     SKIP
     SKIP
@@ -64,12 +64,19 @@ display() {
     configure() {
         if [[ $arch = rm2 ]]; then
             systemctl daemon-reload
-            systemctl enable rm2fb --now
-            # Restart xochitl if it's running
-            if systemctl --quiet is-active xochitl; then
-                # Reset the crash count so we don't trigger remarkable-fail
-                echo "0" > /tmp/crashnum
-                systemctl restart xochitl
+            if systemctl enable rm2fb --now; then
+                # Restart xochitl if it's running
+                if systemctl --quiet is-active xochitl; then
+                    # Reset the crash count so we don't trigger remarkable-fail
+                    echo "0" > /tmp/crashnum
+                    systemctl restart xochitl
+                fi
+            else
+                systemctl disable rm2fb --now
+                echo "Failed to start rm2fb. Keeping it disabled for now."
+                echo "Please check the logs and open an issue:"
+                echo "  https://github.com/toltec-dev/toltec/issues/new"
+                exit 1
             fi
         fi
     }
