kernelctl: reset to default kernel when uninstalling (#691)
* kernelctl: reset to default kernel when uninstalling

* kernelctl: add more safety tests to preremove

---------

Co-authored-by: Nathaniel van Diepen <Eeems@users.noreply.github.com>

diff --git a/package/kernelctl/package b/package/kernelctl/package
--- a/package/kernelctl/package
+++ b/package/kernelctl/package
@@ -5,7 +5,7 @@
 pkgnames=(kernelctl)
 pkgdesc="Manage aftermarket kernels"
 url=https://toltec-dev.org/
-pkgver=0.1-5
+pkgver=0.1-6
 timestamp=2022-11-12T00:00Z
 section="utils"
 maintainer="Salvatore Stella <etn45p4m@gmail.com>"
@@ -29,5 +29,20 @@ configure() {
     if [[ "$(kernelctl list | tail -n +2 | awk '{print $2}' | grep "vanilla-$(< /etc/version)")" == "" ]]; then
         echo "Creating a backup of the currently running kernel."
         kernelctl backup vanilla
+    fi
+}
+
+preremove() {
+    if [[ "$(kernelctl show | tail -n 1 | grep "vanilla-$(< /etc/version)")" == "" ]]; then
+        if [[ "$(kernelctl list | tail -n +2 | awk '{print $2}' | grep "vanilla-$(< /etc/version)")" == "" ]]; then
+            echo "Unable to restore default kernel."
+            echo "To force removal, you can run the following:"
+            echo "  opkg remove --force-remove kernelctl"
+            echo "Warning: This will not leave you in a stock state"
+            exit 1
+        else
+            echo "Restoring default kernel"
+            kernelctl set default
+        fi
     fi
 }
