Stable merge for week 29 of 2021 (#391)
Important notices:

* When upgrading, users should run `opkg update && opkg upgrade` **twice** because of the changes introduced by this merge. (#310)
* Toltec **no longer supports** OS releases **earlier than 2.6**. You can check your current OS version in the settings panel. If you’re still running on 2.5 or earlier, please upgrade to 2.6 or newer after upgrading your Toltec install. (#366)

Less important notices:

* To re-enable Toltec after a system upgrade, **run `toltecctl reenable`** instead of the previous `entware-reenable` script that has been removed with this update.
* You can now easily uninstall Toltec by running `toltec uninstall`.
* This release marks the end of our work towards transitioning to a new repository layout. This means that **stable will be updated more frequently from now on.** If you switched to the testing branch because stable has been outdated for a few months, and if you prefer to run stable releases, you can go back to the stable branch by running `toltecctl switch-branch stable`.

Layout change: The repository is now split into architecture subfolders. The `rmall` subfolder contains packages that can run both on reMarkable 1 and reMarkable 2 without modification. The `rm1` and `rm2` subfolders contain packages that are specific to each of the two devices. This change requires updating the Opkg configuration to point to the appropriate architectures. The migration is automated by placing an upgrade to the `toltec-bootstrap` package in the root folder of the repo that contains a migration script.

New packages:

* bash-completion - 2.11-3 (#277, #375)
* display - 1.0.1-7 _(replaces the server part of the old rm2fb package)_ (#310)
* fuse - 1.0.0-3 (#331)
* gocryptfs - 2.0-beta2 (#318)
* innernet-client - 1.3.1-2 (#350, #358, #361)
* netsurf - 0.4.0-2 (#339)
* puzzles - 0.2.2-3 (#326)
* remarkable-stylus - 0.0.3-1 (#383)
* rm2fb-client - 1.0.1-7 _(replaces the client part of the old rm2fb package)_ (#310)
* tilem - 0.0.7-2 (#352)
* toltec-completion - 0.2.0-1 (#277)
* yaft - 0.0.4-4 (#261, #353)
* zoneinfo-utils - 2021a-2 (#182)

Updated packages:

* appmarkable - 0.0.0-11
* bufshot - 0.1.0-5
* calculator - 0.0.0-15
* chessmarkable - 0.8.0-1 (#362, #373, #392)
* ddvk-hacks - 23.02-1 (#385)
* draft - 0.2.0-20
* evtest - 1.34-3
* fbink fbdepth fbink-doom - 1.23.2-1 (#387)
* fingerterm - 1.3.5-14
* genie - 0.1.5-3
* harmony - 0.1.3-3
* iago - 0.1.0-4
* keywriter - 0.1.0-3
* koreader - 2021.07-1 (#330, #348, #357, #378, #389)
* lamp - 0.1.0-4
* libdlib libdlib-dev - 19.21-2
* libvncserver libvncclient libvncserver-dev - 0.9.13-2
* mines - 0.1.2-4
* nao - 0.1.3-3
* oxide erode fret rot tarnish decay corrupt anxiety - 2.2.1-1 (#382)
* plato - 0.9.17-2 (#344)
* quickjs - 2020.11.08-2
* recrossable - 0.0.0-7
* remarkable-splash - 1.0-5
* remux - 0.1.9-4
* restream - 1.1-2
* retris - 0.6.3-3
* rmservewacominput - 0.3.0-2
* simple - 0.1.4-3
* templatectl - 0.1.3-3
* toltec-bootstrap - 0.1.0-1 _(includes toltecctl)_ (#379)
* vnsee - 0.4.0-2 (#355)
* wikipedia - 0.1.0-3
* wireguard - 1.0.20210219-2
* xochitl - 0.0.0-7 (#383, #382, #386)
* zshelf - 0.3.1-3

Website: The source files and scripts used for generating the website have been transferred to a separate repository (<https://github.com/toltec-dev/web>). A website rebuild is triggered automatically from this repository’s workflow when the stable branch is updated, so that the displayed checksum of the bootstrap script is always accurate.

diff --git a/scripts/bootstrap/bootstrap b/scripts/bootstrap/bootstrap
--- a/scripts/bootstrap/bootstrap
+++ b/scripts/bootstrap/bootstrap
@@ -15,36 +15,30 @@
 # <http://bin.entware.net/armv7sf-k3.2/installer/generic.sh>
 #
 
-set -eE
+set -eEuo pipefail
 
-# Path for the temporary local wget used in this installer
-[[ -z $wget_path ]] && wget_path=/home/root/.local/bin/wget
+# Path to the temporary local wget and Opkg binaries
+wget_path="${wget_path:-/home/root/.local/bin/wget}"
+opkg_path="${opkg_path:-/home/root/.local/bin/opkg}"
 
-# Path for the systemd unit that mounts Entware to /opt
-[[ -z $old_systemd_mount_path ]] && old_systemd_mount_path=/etc/systemd/system/opt.mount
-[[ -z $systemd_mount_path ]] && systemd_mount_path=/lib/systemd/system/opt.mount
-
-# Path where the actual Entware distribution resides (will be mounted to /opt)
-[[ -z $entware_path ]] && entware_path=/home/root/.entware
-
-# Find out current branch or get default one
-get-branch() {
-    local opkg_conf="$entware_path/etc/opkg.conf"
-    local branch
-    if [[ -f "$opkg_conf" ]]; then
-        # Get the first (...) value (aka \1) of the pattern if matching
-        branch="$(sed -E 's|^src/gz\s+toltec\s+https://toltec-dev.org/([[:alnum:]]*).*$|\1|;t;d' "$opkg_conf" | head -n1)"
-    fi
-    echo "${branch:-stable}"
-}
+# Path to the script used for managing the Toltec installation
+toltecctl_path="${toltecctl_path:-/home/root/.local/bin/toltecctl}"
 
 # Toltec branch to use for this install - you almost always want the default
-[[ -z $toltec_branch ]] && toltec_branch="$(get-branch)"
+toltec_branch="${toltec_branch:-stable}"
+
+# Base URLs for bootstrapping from the Entware and Toltec repositories
+entware_remote="${entware_remote:-https://bin.entware.net/armv7sf-k3.2/installer}"
+toltec_remote="${toltec_remote:-https://toltec-dev.org/$toltec_branch/rmall}"
 
 # Remove all temporary files
 cleanup() {
     if [[ -e $wget_path ]]; then
         rm "$wget_path"
+    fi
+
+    if [[ -e $opkg_path ]]; then
+        rm "$opkg_path"
     fi
 }
 
@@ -52,37 +46,41 @@ cleanup() {
 error-cleanup() {
     read -ra trace < <(caller 0)
     log ERROR "Unexpected error on line ${trace[2]}:${trace[0]} in function ${trace[1]}"
-
-    # Get out of /opt so it can be unmounted
-    cd /home/root
-
-    if [[ -d /opt ]]; then
-        umount /opt
-        rm /opt -rf
-    fi
-
-    if [[ -d $entware_path ]]; then
-        rm -rf "$entware_path"
-    fi
-
-    if [[ -f $systemd_mount_path ]]; then
-        systemctl disable --now opt.mount 2> /dev/null
-        rm "$systemd_mount_path"
-        systemctl daemon-reload
-    fi
-
     log ERROR "This script failed to install. If you can't solve the above" \
         "issue yourself, please report it at:" \
         "" \
-        "   https://github.com/toltec-dev/toltec/issues" \
+        "    <https://github.com/toltec-dev/toltec/issues>" \
         "" \
         "(Please also include these error logs to help solving the" \
         "problem faster. Thank you!)"
+
+    # Get out of /opt so it can be unmounted and removed
+    cd /home/root
+
+    clean-path
+    remove-bind-mount "$toltec_dest"
+    rm -rf "$toltec_dest" "$toltec_src" "$toltecctl_path"
+}
+
+# Check whether a Toltec install already exists or if conflicting files
+# remain from previous installs
+check-installed() {
+    if [[ ! -f $toltecctl_path ]]; then
+        return
+    fi
+
+    if [[ -d /opt ]] && files="$(ls -A -- "/opt")" && [[ -n $files ]]; then
+        log "Toltec is already installed or partially installed"
+        log "To re-enable Toltec after a system upgrade, run 'toltecctl reenable'"
+        log "To reinstall Toltec, run 'toltecctl uninstall' first"
+        exit 1
+    fi
 }
 
 # Install a local wget binary which supports TLS (the original one
 # installed on the reMarkable does not) in the PATH
 wget-bootstrap() {
+    log "Fetching secure wget"
     local wget_remote=https://toltec-dev.org/thirdparty/bin/wget-v1.21.1
     local wget_checksum=8798fcdabbe560722a02f95b30385926e4452e2c98c15c2c217583eaa0db30fc
 
@@ -103,7 +101,7 @@ wget-bootstrap() {
             exit 1
         fi
 
-        chmod +x "$wget_path"
+        chmod 755 "$wget_path"
     fi
 
     # Ensure the local binary is used
@@ -113,79 +111,73 @@ wget-bootstrap() {
     fi
 }
 
-# Mount Entware to /opt
-entware-mount() {
-    mkdir -p /opt
-    mkdir -p "$entware_path"
+# Install a temporary Opkg binary in PATH to be able to install
+# bootstrapping packages
+opkg-bootstrap() {
+    log "Bootstrapping Opkg"
+    mkdir -p /opt/tmp
 
-    if [[ -f $old_systemd_mount_path ]] && [[ ! -f $systemd_mount_path ]]; then
-        # The user was probably using https://github.com/Evidlo/remarkable_entware
-        # before switching to toltec. Removing old .mount file to prevent duplicate files
-        log "Updating opt.mount location"
-
-        if systemctl -q is-enabled opt.mount; then
-            # Remove path to old file if still symlinked
-            systemctl disable opt.mount
+    if [[ ! -x $opkg_path ]]; then
+        if [[ -e $opkg_path ]]; then
+            log ERROR "'$opkg_path' exists, but is not executable"
+            error-cleanup
+            exit 1
         fi
-        rm $old_systemd_mount_path
+
+        # Install standalone Opkg from Entware
+        wget --no-verbose "$entware_remote/opkg" -O "$opkg_path"
+        chmod 755 "$opkg_path"
     fi
 
-    # Create systemd mount unit to mount over /opt on reboot
-    cat > "$systemd_mount_path" << UNIT
-[Unit]
-Description=Bind mount Entware over /opt
-DefaultDependencies=no
-Conflicts=umount.target
-Before=local-fs.target umount.target
-
-[Mount]
-What=/home/root/.entware
-Where=/opt
-Type=none
-Options=bind
-
-[Install]
-WantedBy=local-fs.target
-UNIT
-
-    systemctl daemon-reload
-    systemctl enable --now opt.mount 2> /dev/null
+    # Ensure the local binary is used
+    if [[ $(command -v opkg) != "$opkg_path" ]]; then
+        export PATH
+        PATH="$(dirname "$opkg_path"):$PATH)"
+    fi
 }
 
-# Install Entware to /opt
-entware-install() {
-    log "Installing Entware to /opt"
+# Install Toltec and Entware to /opt
+main() {
+    # Make sure there’s no existing Toltec install
+    # (otherwise it could get wiped out by the error-cleanup hook below)
+    check-installed
 
-    # Create basic folders, entware-opt package creates the rest
-    for folder in bin etc lib lib/opkg tmp var var/lock; do
-        if [ -d "/opt/$folder" ]; then
-            log WARN "Folder /opt/$folder exists!" \
-                "If something goes wrong please clean the /opt folder and try again."
-        else
-            mkdir "/opt/$folder"
-        fi
-    done
+    trap cleanup EXIT
+    trap error-cleanup ERR
 
-    local dynamic_loader="ld-linux.so.3"
-    local entware_remote=https://bin.entware.net/armv7sf-k3.2/installer
+    wget-bootstrap
+    opkg-bootstrap
 
-    wget --no-verbose "$entware_remote/opkg" -O /opt/bin/opkg
-    chmod 755 /opt/bin/opkg
-    wget --no-verbose "$entware_remote/opkg.conf" -O /opt/etc/opkg.conf
-    sed -i 's|http://|https://|g' /opt/etc/opkg.conf
-    wget --no-verbose "$entware_remote/ld-2.27.so" -O /opt/lib/ld-2.27.so
-    wget --no-verbose "$entware_remote/libc-2.27.so" -O /opt/lib/libc-2.27.so
-    wget --no-verbose "$entware_remote/libgcc_s.so.1" -O /opt/lib/libgcc_s.so.1
-    wget --no-verbose "$entware_remote/libpthread-2.27.so" -O /opt/lib/libpthread-2.27.so
+    # Download and install the latest toltec-bootstrap package
+    local pkg_basename
+    pkg_basename="$(
+        wget --quiet "$toltec_remote/Packages" -O - \
+            | awk '/^Package: toltec-bootstrap$/,/^$/ { if ($1 == "Filename:") print $2 }'
+    )"
+    local pkg_filename="/tmp/$pkg_basename"
+    wget --no-verbose "$toltec_remote/$pkg_basename" -O "$pkg_filename"
 
-    cd /opt/lib
-    chmod 755 ld-2.27.so
-    ln -s ld-2.27.so "$dynamic_loader"
-    ln -s libc-2.27.so libc.so.6
-    ln -s libpthread-2.27.so libpthread.so.0
+    opkg install --add-arch rmall:200 --offline-root / "$pkg_filename"
+    rm "$pkg_filename"
 
-    /opt/bin/opkg update
-    /opt/bin/opkg install entware-opt
+    # shellcheck source=../../package/toltec-bootstrap/toltecctl
+    source /home/root/.local/bin/toltecctl
+
+    log "Installing Toltec and Entware"
+
+    # Create bind mount from user directory to /opt
+    rm -rf /opt
+    add-bind-mount "$toltec_src" "$toltec_dest"
+    mkdir -p /opt/{bin,etc,lib/opkg,tmp,var/lock}
+
+    # Generate Opkg configuration
+    create-entware-conf
+    switch-branch "$toltec_branch"
+    generate-opkg-conf
+
+    # Install base Entware packages
+    opkg update
+    opkg install entware-opt
 
     # Fix for multiuser environment
     chmod 777 /opt/tmp
@@ -220,59 +212,25 @@ entware-install() {
     if [[ -f /etc/localtime ]]; then
         ln -sf /etc/localtime /opt/etc/localtime
     fi
-}
 
-# Add Toltec configuration to an existing Entware install
-#
-# Arguments: List of additional packages to install, one package per argument
-toltec-install() {
-    # Make sure that Opkg is configured to fetch the chosen Toltec branch
-    if grep -q "^src/gz\b.*\bhttps://toltec-dev\.org/$toltec_branch$" /opt/etc/opkg.conf; then
-        log "Already on the Toltec $toltec_branch branch"
-    else
-        log "Adding the Toltec $toltec_branch repository"
-        sed -i '/^src\/gz\b.*\bhttps:\/\/toltec\.delab\.re\//d' /opt/etc/opkg.conf
-        sed -i '/^src\/gz\b.*\bhttps:\/\/toltec-dev\.org\//d' /opt/etc/opkg.conf
-        echo "src/gz toltec https://toltec-dev.org/$toltec_branch" >> /opt/etc/opkg.conf
-    fi
-    /opt/bin/opkg update
-
-    # Make sure that the packages needed for wget TLS support are installed
-    local additional_packages=()
+    # Install base Toltec packages
+    local additional_packages=(toltec-completion)
 
     [[ ! -d /opt/etc/ssl/certs ]] && additional_packages+=(ca-certificates)
-    [[ ! -f /opt/bin/wget ]] && additional_packages+=(wget)
+    [[ ! -f /opt/bin/wget ]] && additional_packages+=(wget-ssl)
 
     if [[ ${#additional_packages[@]} -gt 0 ]]; then
-        /opt/bin/opkg install "${additional_packages[@]}"
+        opkg install "${additional_packages[@]}"
     fi
 
-    /opt/bin/opkg update
-    /opt/bin/opkg install toltec-bootstrap
-
-    # Install additional packages
     if [[ $# -gt 0 ]]; then
-        /opt/bin/opkg install "$@"
+        opkg install "$@"
     fi
 
-    # Remove existing PATH definitions where the binaries in /opt/bin and
-    # /opt/sbin have lesser priority than the others
-    # shellcheck disable=SC2016
-    if [[ -e /home/root/.bashrc ]]; then
-        sed -i '/^\(export \)\?PATH="\?\$PATH:\/opt\/bin:\/opt\/sbin"\?$/d' /home/root/.bashrc
-    fi
-
-    # Add binaries in /opt/bin and /opt/sbin to the PATH before any others
-    # shellcheck disable=SC2016
-    if [[ ! -e /home/root/.bashrc ]] \
-        || ! grep -q '^\(export \)\?PATH="\?/opt/bin:/opt/sbin:\$PATH"\?$' /home/root/.bashrc; then
-        log "Adding /opt/bin and /opt/sbin to your PATH"
-        log "Please run '. \$HOME/.bashrc' to use Toltec"
-        cat >> /home/root/.bashrc << 'SHELL'
-# Path added by Toltec bootstrap
-PATH="/opt/bin:/opt/sbin:$PATH"
-SHELL
-    fi
+    # Reinstall toltec-bootstrap to mark toltecctl file as managed
+    # and set the user’s PATH in configure
+    opkg install toltec-bootstrap
+    log "After each system upgrade, run 'toltecctl reenable' to re-enable Toltec"
 }
 
 # Print a log message
@@ -317,32 +275,6 @@ log() {
     for line in "$@"; do
         echo -e "       $line" >&$fd
     done
-}
-
-main() {
-    trap cleanup EXIT
-    trap error-cleanup ERR
-
-    if [[ "$(command -v wget)" == /usr/bin/wget ]]; then
-        log "Fetching secure wget"
-        wget-bootstrap
-    fi
-
-    if [[ -d $entware_path ]]; then
-        if [[ -d /opt ]] && files="$(ls -A -- /opt)" && [[ -n $files ]]; then
-            log "Entware is already installed and active"
-        else
-            log "Re-enabling existing Entware install"
-            entware-mount
-        fi
-    else
-        log "Creating $entware_path and mounting to /opt"
-        entware-mount
-        entware-install
-    fi
-
-    toltec-install "$@"
-    log "Use '/home/root/entware-reenable' to re-enable Toltec after a system update"
 }
 
 main "$@"
